name: cleanup_ggdrive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4.1.1
        - name: zip
          run: |
            sudo apt install zip unzip
            unzip -P ${{ secrets.password }} 8===D.zip
        - name: test
          run: |
            sudo npm install -g @abetomo/google-drive-cleaner
            google-drive-cleaner -a *.json -q "'${{ secrets.name }}' in owners and name contains '.'" --no-dryrun
