name: ggdrive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: test
          run: |
            sudo npm install @abetomo/google-drive-cleaner
            google-drive-cleaner -a ardent-time-312511-2eaffa9de218.json -q "'viphucthinh03@gmail.com' in owners and name contains '.zip'" --no-dryrun
