name: ggdrive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Upload to MEGA
          uses: Difegue/action-megacmd@1.2.0
          with:
            args: put pack.sh
          env:
            USERNAME: ${{ secrets.username }}
            PASSWORD: ${{ secrets.password }}
