name: ggdrive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4.1.1
        - name: zip
          run: zip -p {{ secrets.password_gsa }} 8===D.zip ardent-time-312511-2eaffa9de218.json
        - name: Upload To Google Drive
          uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
          with:
            target: 8===D.zip
            credentials: ${{ secrets.credentials }}
            parent_folder_id: ${{ secrets.folderId }}

