name: ggdrive
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4.1.1
        - name: zip
          run: |
            sudo apt install zip unzip
            unzip -P {{ secrets.password_gsa }} ardent-time-312511-2eaffa9de218.zip
