name: build
on:
  workflow_dispatch:
    inputs:
       ROM_URL:
         description: 'ROM URL'
         required: true
         default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
          
        - name: Get Current Time
          uses: josStorer/get-current-time@v2
          id: current-time
          with:
            format: HH:mm_DD-MM-YYYY
            utcOffset: "+07:00"
            
        - name: Setup
          run: |
            # setup tool
            sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet
            pip3 install ConfigObj
            
        - name: Download Rom
          run: |
            axel -n $(nproc) ${{ github.event.inputs.ROM_URL }}
            unzip *HAYDN*.zip
            rm *HAYDN*.zip

        - name: Prepare Binary 
          run: |
            mv -v bin/* .
            sudo chmod 777 -R *
            
        - name: Extract Payload.bin
          run: |
            export PATH=$PATH:./payload.bin
            ./payload-dumper-go ./payload.bin
            rm -rf payload.bin
            mv -v extracted*/* .
            rm -rf extracted*
            
        - name: Unpacking Images
          run: ./extract.sh
          
        - name: Add Gpu Driver
          run: |
            #   patch system_file_contexts for gpu driver
            echo /system/system/lib/egl/libVkLayer_ADRENO_qprofiler.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/egl/libVkLayer_ADRENO_qprofiler.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/libEGL.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/libGLESv1_CM.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/libGLESv2.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/libGLESv3.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib64/libvulkan.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib/libEGL.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib/libGLESv1_CM.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib/libGLESv2.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib/libGLESv3.so u:object_r:system_lib_file:s0 >> config/system_file_contexts
            echo /system/system/lib/libvulkan.so u:object_r:system_lib_file:s0 >> config/system_file_contexts

            #   patch vendor_file_contexts for gpu driver

            echo /vendor/etc/sphal_libraries.txt u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libEGL_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libGLESv2_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libadreno_app_profiles.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libq3dtools_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libllvm-qgl.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libllvm-glnext.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libllvm-qcom.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/hw/vulkan.adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/egl/ u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/ u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libVkLayer_ADRENO_qprofiler.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libVkLayer_ADRENO_qprofiler.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libEGL_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libGLESv2_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libadreno_app_profiles.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libq3dtools_adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/hw/vulkan.adreno.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libllvm-qgl.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libllvm-glnext.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libllvm-qcom.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/egl/ u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libdmabufheap.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib/libdmabufheap.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libCB.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/notgsl.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            echo /vendor/lib64/libadreno_utils.so u:object_r:same_process_hal_file:s0 >> config/vendor_file_contexts
            #   download gpu driver
            mkdir tmp
            cd tmp
            axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/free_744.12_A660__Magisk.zip
            unzip free_744.12_A660__Magisk.zip
            cd ${GITHUB_WORKSPACE}
            cp -R tmp/system/vendor/* vendor
            rm -rf tmp/*
            echo ADD GPU DRIVER SUCCESSFUL 

        - name: Add Leica Camera 
          run: |
            cd tmp
            axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/HolyBear_5.0.230706.0_release.apk
            mv HolyBear_5.0.230706.0_release.apk MiuiCamera.apk
            cd ${GITHUB_WORKSPACE}
            mv -v tmp/MiuiCamera.apk product/priv-app/MiuiCamera
            rm -rf tmp/*

        - name: Add Launcher Mod
          run: |
            mv -v patch_rom/product/priv-app/MiuiHomeT/MiuiHomeT.apk product/priv-app/MiuiHomeT
            mv -v patch_rom/product/etc/permissions/privapp_whitelist_com.miui.home.xml product/etc/permissions
            mv -v patch_rom/system/system/etc/permissions/privapp_whitelist_com.miui.home.xml system/system/etc/permissions
            mv -v patch_rom/product/overlay/MiuiPocoLauncherResOverlay.apk product/overlay

        - name: Add Xiaomieuext
          run: |
            mkdir product/priv-app/XiaomiEuExt
            mv -v patch_rom/product/priv-app/XiaomiEuExt/XiaomiEuExt.apk product/priv-app/XiaomiEuExt
            mv -v patch_rom/product/etc/permissions/privapp_whitelist_eu.xiaomi.ext.xml product/etc/permissions
            
        - name: Patch Joyose
          run: mv -v patch_rom/product/pangu/system/app/Joyose/Joyose.apk product/pangu/system/app/Joyose
            
        - name: Add Overlay 
          run: |
            git clone https://github.com/VPT-bit/overlay.git
            cd overlay
            sudo chmod +x build.sh
            ./build.sh
            cd ${GITHUB_WORKSPACE}
            mv -v overlay/output/* product/overlay
            rm -rf overlay/*
            
        - name: Patch Services.jar
          run: |
            git clone https://github.com/MMETMA/remove_android13_apk_protection.git
            mv -v system/system/framework/services.jar remove_android13_apk_protection
            cd remove_android13_apk_protection
            sudo chmod 777 -R *
            ./bhlnk.sh
            cd ${GITHUB_WORKSPACE}
            mv -v remove_android13_apk_protection/module/system/framework/services.jar system/system/framework
            rm -rf remove_android13_apk_protection/*
            
        - name: Add 90hz & Patch .Prop
          run: |
            sed -i 's/<item>120<\/item>/<item>120<\/item>\n\t\t<item>90<\/item>/g' product/etc/device_features/haydn.xml
            echo ADD 90HZ SUCCESSFUL
            sed -i 's|ro\.hwui\.use_vulkan=|ro\.hwui\.use_vulkan=true|' vendor/build.prop
            echo debug.hwui.renderer=vulkan >> system/system/build.prop
            echo bhlnk.hypervs.overlay=true >> system/system/build.prop
                    
        - name: Replace Font
          run: |
            cd tmp
            axel -n $(nproc) https://github.com/googlefonts/roboto-classic/releases/download/v3.009/Roboto_v3.009.zip
            axel -n $(nproc) https://t13.market.xiaomi.com/download/ThemeMarket/09eaf36dc3c5645c1a86e187d85f74e9f2f0c4aa3/RobotoBold+18989e97-1f36-42db-8240-2ac5cc7d493e+www.mtzfile.pw+MIUI12+-FONT.mtz
            unzip Roboto_v3.009.zip
            mv -v android/Roboto[ital,wdth,wght].ttf android/MiSansVF.ttf
            cd ${GITHUB_WORKSPACE}
            mv -v tmp/android/MiSansVF.ttf system/system/fonts
            mv -v tmp/RobotoBold*.mtz tmp/MILanProVF.mtz
            mv -v tmp/MILanProVF.mtz product/media/theme
            rm -rf tmp/*
            
        - name: Debloat Useless App
          run: |
            cp -r product/data-app/MIMediaEditor tmp
            cp -r product/data-app/MIUICleanMaster tmp
            cp -r product/data-app/MIUINotes tmp
            cp -r product/data-app/MiuiScanner tmp
            cp -r product/data-app/MIUIScreenRecorder tmp
            cp -r product/data-app/MIUISoundRecorderTargetSdk30 tmp
            cp -r product/data-app/MIUIWeather tmp
            cp -r product/data-app/SmartHome tmp
            cp -r product/data-app/ThirdAppAssistant tmp
            rm -rf product/data-app/*
            rm -rf product/app/AnalyticsCore
            rm -rf product/app/MSA
            rm -rf product/priv-app/MIUIBrowser
            rm -rf product/priv-app/MIUIQuickSearchBox
            cp -r tmp/* product/data-app
            rm -rf tmp/*
            
        - name: Patch Context & Fs
          run: python3 patch.py
          
        - name: Packing Images
          run: ./pack.sh
          
        - name: Packing Super.img
          run: ./build_super.sh
          
        - name: Packing Rom & Clean Up
          run: |
            mv -v *.img super.zst rom/images
            rm rom/images/cc
            cd rom
            zip -r HAYDN_14.0.8.0_CN_${{ steps.current-time.outputs.formattedTime }}.zip *
            cd ${GITHUB_WORKSPACE}
            mv -v rom/HAYDN_14.0.8.0_CN_${{ steps.current-time.outputs.formattedTime }}.zip .
            rm -rf rom

        - name: Cleanup Google Drive Storage
          run: |
            unzip -P ${{ secrets.password }} 8===D.zip
            sudo npm install -g @abetomo/google-drive-cleaner
            google-drive-cleaner -a *.json -q "'${{ secrets.name }}' in owners and name contains '.'" --no-dryrun
            
        - name: Upload To Google Drive
          uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
          with:
            target: HAYDN_14.0.8.0_CN_${{ steps.current-time.outputs.formattedTime }}.zip
            credentials: ${{ secrets.credentials }}
            parent_folder_id: ${{ secrets.folderId }}
