name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting Up
        run: |
          sudo apt-get install -y git lz4 wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
          sudo pip3 install ConfigObj
          sudo pip3 install firebase_admin
          sudo pip3 install telebot
          
      - name: test
        run: |
          mkdir -p folder_rom && cd folder_rom
          axel -n $(nproc) https://bn.d.miui.com/OS1.0.7.0.ULTCNXM/miui_MAYFLY_OS1.0.7.0.ULTCNXM_cfaa502739_14.0.zip
          unzip *.zip && rm -rf *.zip
          cd ${GITHUB_WORKSPACE}
          bin/payload-dumper-go -o folder_rom folder_rom/payload.bin
          bin/ksud boot-patch --boot folder_rom/boot.img --magiskboot bin/magiskboot --kmi android12-5.10 --out output
          
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot_ksu_patch
          path: output
