name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: test
          run: |
              sudo apt update -y
              sudo apt upgrade -y
              sudo apt-get install -y python3
              pip install DriveDownloader
              ddl https://1drv.ms/f/s!Aizo2bT9Zr2NcM8F8tOV4z4XzwY
              
