name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: test
          run: |
              sudo apt update -y
              sudo apt upgrade -y
              sudo apt-get install -y python3
              pip install DriveDownloader
              pip install -r requirements.txt
              
