name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        run: |
          sudo apt-get install -y axel
          mkdir -p tmp
          cd tmp
          axel -n $(nproc) https://cdn-ota.azureedge.net/OS1.0.7.0.UMCCNXM/miui_FUXI_OS1.0.7.0.UMCCNXM_78af83b0a0_14.0.zip

      - name: Upload README.md to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: 'tmp/*.zip'
          credentials: ${{ secrets.credentials }}
          folder: ${{ secrets.folderId }}
