name: test
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test
        run: |
          output=$(awk '/\.registers/,/\.end method/' "test.txt")
          echo $output
