name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: Set Up JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'
        - name: test
          run: sudo bash test.sh
