name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH-DDMMYYYY
          utcOffset: "+07:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: | 
            echo $TIME
            echo "cut -d ' ' -f 2,3,4 $R_TIME"             
            echo $F_TIME  
            echo $YEAR
            echo $DAY
