name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss-DD/MM/YYYY
          utcOffset: "+07:00"
      - name: Use current time
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $F_TIME
      - name: test
        run: echo $F_TIME
