name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HHhmm'ss"-DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        run: echo ${{ steps.current-time.outputs.formattedTime }}
