name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        run: |
          sudo apt-get install -y axel
          mkdir -p tmp
          cd tmp
          axel -n $(nproc) https://cdn-ota.azureedge.net/OS1.0.7.0.UMCCNXM/miui_FUXI_OS1.0.7.0.UMCCNXM_78af83b0a0_14.0.zip
        env:
          haha: cai lon
      - name: cc
        run: |
          if test tmp/*.zip; then
          echo con cac
          fi
          echo ${{ env.haha }}
          
      - name: Upload a file to Google Drive
        
        uses: willo32/google-drive-upload-action@v1
        with:
          target: "tmp/*.zip"
          credentials: ${{ secrets.credentials }}
          parent_folder_id: ${{ secrets.folderId }}

