name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: encode
        run: |
          cd ${GITHUB_WORKSPACE}
          sudo chmod 777 -R *
          sudo base64 ardent-time-312511-2eaffa9de218.json -w0 > credentials.txt
      - name: UPLOAD TO GOOGLE DRIVE
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "credentials.txt"
          folderId: ${{ secrets.folderId }}
