name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: setup
          run: |
              sudo apt update
              sudo apt install curl -y
  
        - name: test
          run: |
              sudo bash setup.sh
