name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: test
          run: |
              sudo apt update -y
              sudo apt upgrade -y
              sudo apt-get install -y axel curl wget
              wget https://1drv.ms/u/s!Aizo2bT9Zr2NccIte5kD-CD4zKY?e=dRhvrJ
              
