name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
  
        - name: test
          run: |
            sudo bash test.sh
            
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: oat
            path: oat/*
