name: Building Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git
          kernel-branch: mayfly-s-oss
          config: mayfly_GKI.config
          arch: arm64
          ksu-other: true
          ksu-url: https://github.com/rifsxd/KernelSU-Next.git
          extra-cmd: true
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r487747
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
