name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        run: |
          echo ${{ secrets.credentials }} >> credentials.txt
          echo ${{ secrets.folderId }} >> folderId.txt
          mkdir tmp
          mv folderId.txt tmp
          mv credentials.txt tmp
          cd tmp
          zip -r cc.zip *
          cd ${GITHUB_WORKSPACE}
          zip_file=$(find tmp -type f -name "*.zip")
          name=$(basename $zip_file | cut -d '.' -f 1)
          echo $zip_file
          echo $name

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: tmp/*.zip
          folderId: ${{ secrets.folderId }}
