name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        run: |
          echo ${{ secrets.credentials }} >> credentials.txt
          echo ${{ secrets.folderId }} >> folderId.txt
          mkdir tmp
          mv folderId.txt tmp
          mv credentials.txt tmp
          cd tmp
          zip -r cc.zip *
          zip_file=$(find ./tmp -type f -name "*.zip" -print -quit | basename)
      - name: Upload To Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: tmp/$zip_file.zip
          credentials: ${{ secrets.credentials }}
          parent_folder_id: ${{ secrets.folderId }}
