name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting Up
        run: |
          sudo apt-get install -y git lz4 wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
          sudo pip3 install ConfigObj
          sudo pip3 install firebase_admin
          sudo pip3 install telebot
          
      - name: test
        run: |
          sudo chmod 777 -R *
          java -jar bin/apktool/apktool_2.9.3.jar d rom/MiuiHome.apk -o tmp
          
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk_decode
          path: tmp/*
