name: test
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test
        run: |
          method_name="setScreenEffect"
          new_method_content=".registers 4\n\treturn-void"
          sed -i "/\.method*$method_name/,/\.end method/s/\.registers[^\n]*$/$new_method_content/" test.txt
          cat test.txt
