name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: setup binary
          run: sudo apt-get install git
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: 17
        - uses: gradle/actions/setup-gradle@v3.4.1
          with:
            dependency-graph: generate-and-submit
        - name: test
          run: sudo bash test.sh
