name: test
on:
  workflow_dispatch:
    inputs:
       ROM_URL:
         description: 'ROM URL'
         required: true
         default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
        - name: Checkout
          uses: actions/checkout@main
            
        - name: Setting Up
          run: |
                sudo apt update
                sudo apt upgrade
                sudo apt install git -y
                git clone https://github.com/toraidl/hyperos_port.git
                cd hyperos_port
                sudo ./setup.sh
                
        - name: Build
          run: |
                if [[ -f build.sh ]]; then
                    cp -rf build.sh hyperos_port
                else
                    echo "loi"
                fi
                cd hyperos_port
                sudo ./build.sh ${{ github.event.inputs.ROM_URL }}
                echo "name_rom=$(find out -type f -name *.zip)" >> $GITHUB_ENV

        - name: Cleanup Google Drive Storage
          run: |
            unzip -P ${{ secrets.password }} 8===D.zip
            sudo npm install -g @abetomo/google-drive-cleaner
            google-drive-cleaner -a *.json -q "'${{ secrets.name }}' in owners and name contains '.'" --no-dryrun

        # - name: Upload To Google Drive
        #   uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        #   with:
        #     target: ${name_rom}
        #     credentials: ${{ secrets.credentials }}
        #     parent_folder_id: ${{ secrets.folderId }}
        - name: test
          run: |
            echo "rom name: ${name_rom}"
