name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: test
          run: |
            stock_rom="miui_HAYDN_V14.0.8.0.TKKCNXM_e3deaf183b_13.0.zip"
            codename=$(echo $stock_rom | cut -d '_' -f 2)
            miui_version=$(echo $stock_rom | cut -d '_' -f 3 | sed 's/........$//')
            miui_info=$(echo $stock_rom | cut -d '_' -f 3)
            android_version=$(echo $stock_rom | cut -d '_' -f 5 | cut -d '.' -f 1)
            echo $codename 
            echo $miui_version
            echo $android_version
