name: test_smali
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: test
        run: |
          sudo apt install axel apktool
          cd rom/images
          axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/com.miui.powerkeeper_4.2.00-40200_minAPI33.nodpi._apkmirror.com.apk
          mv -v com.miui.powerkeeper*.apk PowerKeeper.apk
          apktool d rom/images/PowerKeeper.apk -o tmp
      - uses: actions/upload-artifact@v3
        with:
          name: powerkeeper
          path: ./rom/images/*
