name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: Setting up
          run: |
            sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet apktool aapt
            pip3 install ConfigObj
        - name: test
          run: |
            java -jar bin/apktool/apktool_2.9.3.jar d System*.apk -o output
        - name: artifact
          uses: actions/upload-artifact@v4
          with:
            path: output/*
