name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup
        run: |
          sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet apktool
          pip3 install ConfigObj
          
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: download
        run: |
          echo ${{ steps.current-time.outputs.formattedTime }}
          axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/PowerKeeper.apk
          sudo chmod 777 -R *
      - name: test
        run: ./fps.sh
