name: test
on:
  workflow_dispatch:
    inputs:
       ROM_URL:
         description: 'ROM URL'
         required: true
         default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: maximizeYourBuildEnvironment
          uses: easimon/maximize-build-space@master
          with:
              swap-size-mb: 8192
              root-reserve-mb: 4096
              temp-reserve-mb: 4096
              remove-dotnet: 'true'
              remove-android: 'true'
              remove-haskell: 'true'
             
        - name: Checkout
          uses: actions/checkout@main
            
        - name: Setting Up
          run: |
              sudo bash setup.sh
              
        - name: Download ROM & Check Binaries
          run: |
              sudo bash download_check.sh ${{ github.event.inputs.ROM_URL }}

        - name: Unpack ROM
          run: |
              sudo bash unpack.sh

        - name: Patch ROM
          run: |
              sudo bash patch.sh

        - name: Repack ROM
          run: |
              sudo bash repack.sh
              
        - name: Cleanup Google Drive Storage
          run: |
            unzip -P ${{ secrets.password }} 8===D.zip
            sudo npm install -g @abetomo/google-drive-cleaner
            google-drive-cleaner -a *.json -q "'${{ secrets.name }}' in owners and name contains '.'" --no-dryrun

        # - name: Upload To Google Drive
        #   uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        #   with:
        #     target: ${name_rom}
        #     credentials: ${{ secrets.credentials }}
        #     parent_folder_id: ${{ secrets.folderId }}
