name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: setup
          run: sudo apt-get install axel sed
        - name: test
          run: |
            axel -n $(nproc) https://www.tgxhub.workers.dev/dl/6657ee67b6fab2e79cd3562f
            for file in $(find . -type f -name *.apk); do
              echo $file
            done
