name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
  
        - name: test
          run: |
            /system/bin/dex2oat --help
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: apk
            path: output/*
