name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: setup
          run: sudo apt-get install axel
        - name: test
          run: |
            mkdir -p ./test_folder
            cp test.sh test_folder
            cd test_folder
            axel -n $(nproc) https://www.tgxhub.workers.dev/dl/6656cbbdeec534e878674534
            sudo bash test.sh
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            path: ./PowerKeeper.apk
