name: test_smali
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: test
        run: |
          sudo bash test.sh
      - uses: actions/upload-artifact@v3
        with:
          name: powerkeeper
          path: rom/images/PowerKeeper.apk
