name: Building Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ztc1997/android_gki_kernel_5.10_common.git
          kernel-branch: android12-5.10-2024-11
          config: gki_defconfig defconfig
          arch: arm64
          extra-cmd: true
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r487747c
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
