name: test2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main
  
        - name: test
          run: |
              cd /
              sudo chmod 777 -R * > /dev/null 2>&1
              for file in $(find . -type f -name *dex2oat* > /dev/null 2>&1); do
                  echo "found in path: $file"
              done
              
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: output
            path: output/*
