name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: |
          echo "NOW=Get-Date -format "yyyy-MM-dd"" >> $GITHUB_ENV
          echo ${{ env.NOW }}
