name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting Up
        run: |
          sudo apt-get install -y git lz4 wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
          sudo pip3 install ConfigObj
          sudo pip3 install firebase_admin
          sudo pip3 install telebot
          
      - name: test
        run: |
          sudo chmod 777 -R *
          mkdir -p temp
          cp -rf MiuiHome.apk temp/MiuiHome.zip
          cd ${GITHUB_WORKSPACE}
          java -jar bin/apktool/apktool_2.9.3.jar d MiuiHome.apk -o tmp || echo "Decode failed"
          sed -i "s/<property android:name=\"miui.blurRelaunch\" android:value=\"true\"\/>//g" tmp/AndroidManifest.xml
          sed -i "s/<property android:name=\"android.view.PROPERTY_MIUI_SMOOTH_CORNER_ENABLED\" android:value=\"true\"\/>//g" tmp/AndroidManifest.xml
          rm -rf tmp/res
          java -jar bin/apktool/apktool_2.9.3.jar b tmp -o tmp/repack/MiuiHome_repack.zip || echo "Repack failed"
          cd tmp/repack
          unzip MiuiHome_repack.zip
          cd ${GITHUB_WORKSPACE}
          cp -rf tmp/repack/AndroidManifest.xml temp/AndroidManifest.xml
          cd temp
          zip -r MiuiHome.apk AndroidManifest.xml
          cd ${GITHUB_WORKSPACE} 
          ./zipalign -p -f -v 4 temp/MiuiHome.apk temp/MiuiHome_mod.apk || echo "Zipalign failed"
          
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk_decode
          path: temp/MiuiHome_mod.apk
