name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: HH:mm:ss_DD-MM-YYYY
          utcOffset: "+07:00"
      - name: test
        id: cc
        run: |
          sudo apt-get install -y axel
          mkdir -p tmp
          cd tmp
          axel -n $(nproc) https://cdn-ota.azureedge.net/OS1.0.7.0.UMCCNXM/miui_FUXI_OS1.0.7.0.UMCCNXM_78af83b0a0_14.0.zip
          cd ${GITHUB_WORKSPACE}
          echo "path_zip=$(find tmp -type f -name "*.zip")" >> "$GITHUB_ENV"
           
      - name: cccc
        run: |
          if test tmp/*.zip; then
          echo con cac
          fi
          echo ${path_zip}
          echo  
          echo ${{ env.path_zip }}
        
      - name: Upload To Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: ${{ env.path_zip }}
          credentials: ${{ secrets.credentials }}
          parent_folder_id: ${{ secrets.folderId }}
