name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Maximize Build Space
          uses: easimon/maximize-build-space@master
          with:
            root-reserve-mb: 512
            swap-size-mb: 1024
            remove-dotnet: "true"
            remove-android: "true"
            remove-haskell: "true"
            
        - name: Checkout
          uses: actions/checkout@main
            
        - name: Setting Up
          run: |
            sudo apt-get install -y git lz4 wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
            sudo pip3 install ConfigObj
            sudo pip3 install firebase_admin
            sudo pip3 install telebot
            
        - name: download
          run: |
            cat >> test.smali
            sudo bash test.sh
            cat >> test.smali
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: apk_extracted
            path: tmp/*
