name: test
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting Up
        run: |
          sudo apt-get install -y git lz4 wget zip unzip android-sdk-libsparse-utils brotli axel python3-pip zipalign apksigner xmlstarlet vim aapt p7zip-full
          sudo pip3 install ConfigObj
          sudo pip3 install firebase_admin
          sudo pip3 install telebot
      - name: ban dau
        run: cat test.txt
      - name: sau khi va method
        run: |
          sudo bash test.sh
          cat test.txt
