name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Put current date into a variable
        run: |
          NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV
      - name: Use variable
        run: |
          echo "${{env.NOW}}"
